accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "accounts"

urlpatterns = [
    path("login/", LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout")
]

menu/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home")
]

organizador/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tareas/', include('tareas.urls')),
    path('', include('menu.urls')),
    path('', include('accounts.urls'))
]

tareas/urls.py
from django.urls import path
from . import views

app_name = "tareas"

urlpatterns = [
    path("", views.home, name="index")
]

tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/", views.task, name="task"),
    path("create-task/", views.createTask, name="create-task"),
    path("update-task/<int:pk>/", views.updateTask, name="update-task")
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class CustomUser(AbstractUser):
    pass

menu/models.py
from django.db import models

# Create your models here.

tareas/models.py
from django.db import models

# Create your models here.

tasks/forms.py
from django.forms import ModelForm
from .models import Task

class createTask(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'limit_date']

accounts/views.py
from django.shortcuts import render

# Create your views here.
def login_view(request):
    return render(request, "accounts/login.html")

menu/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, "menu/home.html")

tareas/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


# Create your views here.

#@login_required
def home(request):
    return render(request, "tareas/index.html")
 

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import TaskForm
from .models import Task

# Create your views here.

#@login_required
def index(request):
    tasks = Task.objects.filter(user=request.user).order_by("-id")
    context = {"tasks": tasks}
    return render(request, "tasks/index.html", context)

@login_required
def task(request, pk):
    task = get_object_or_404(Task, id=pk, user=request.user)

    return render(request, "tasks/task.html", {"task": task})

@login_required
def createTask(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            return redirect('tasks:index')
    else:
        form = TaskForm()

    return render(request, "tasks/form.html", {"form": form})


@login_required
def updateTask(request, pk):
    task = get_object_or_404(Task, id=pk, user=request.user)

    if request.method =="POST":
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect("tasks:index")
    else:
        form = TaskForm(instance=task)
    return render(request, "tasks/form.html", {"form": form})

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
WIIIIIIIIIIIIIIIIIIIIII

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Entrar</button>
</form>
{% endblock content %}

menu/templates/menu/home.html
{% extends 'base.html' %}

{% block content %}
HOLAAAAA

<a href="{% url 'tasks:index' %}">Tasks</a>
<a href="{% url 'accounts:login' %}">Login</a>
{% endblock content %}

tareas/templates/tareas/index.html
Estás en tareas.

tasks/templates/tasks/form.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">
        {% if form.instance.pk %}
            Update
        {% else %}
            Create
        {% endif %}
    </button>
</form>
{% endblock content %}

tasks/templates/tasks/index.html
{% extends 'base.html' %}

{% block content %}
Estás en Tasks.
<a href="{% url 'tasks:create-task' %}">Create Task</a>
<hr>
{% for task in tasks %}
    <div> 
        <h3>
            <a href="{% url 'tasks:task' task.pk %}">{{task.title}}</a>
        </h3>
        <p>{{task.description}}</p>
        <p>completado: {{task.completed}}</p>
        <small>fecha límite: {{task.limit_date}}</small>
        <a href="{% url 'tasks:update-task' task.pk %}">Update task</a>
    </div>
    <hr>
{% endfor %}

{% endblock content %}

tasks/templates/tasks/task.html
{% extends 'base.html' %}

{% block content %}

<h1>{{task.title}}</h1>
<p>{{task.description}}</p>
<p>completado: {{task.completed}}</p>
<small>fecha límite: {{task.limit_date|date:"d/m/Y H:i"}}</small>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    
    {% endblock content %}
</body>
</html>